name: invoice_formatter
description: "A library for professionally formatting and organizing invoices in Flutter applications. The library helps in creating organized invoices, generating them as PDF files, and customizing them in a flexible way."
version: 0.0.1
author: -"mosab Youssef <ms3byoussef@gmail.com>"  

homepage: "https://github.com/ms3byoussef/invoice_formatter"  # عنوان صفحة GitHub أو الموقع الخاص بالمكتبة.

repository: "https://github.com/ms3byoussef/invoice_formatter"  # رابط مستودع GitHub.

issue_tracker: "https://github.com/ms3byoussef/invoice_formatter/issues"  # رابط صفحة المشاكل على GitHub.


environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  barcode_widget: ^2.0.4
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
